# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ![Welcome Banner](https://raw.githubusercontent.com/data-umbrella/info/main/images/welcome-bot/BannerCongratulations.jpg)
  
  :tada: Welcome to _Data Umbrella_! :tada:
  We're really excited to have your input into the project! :sparkling_heart: ðŸ’–

  <br>If you haven't done so already, please make sure you check out our [Contributing Guidelines](https://github.com/data-umbrella/event-transcripts/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/data-umbrella/event-transcripts/blob/main/CODE_OF_CONDUCT.md).


# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ![Thank You Banner](https://github.com/data-umbrella/info/blob/main/images/welcome-bot/BannerThanks.jpg?raw=true)

  :sparkling_heart: Thanks for opening this pull request! :sparkling_heart: ðŸ’–
  _Data Umbrella_ community really appreciates your time and effort to contribute to the project.
  Please make sure you have read our [Contributing Guidelines](https://github.com/data-umbrella/event-transcripts/blob/main/CONTRIBUTING.md) and filled in our pull request template to the best of your ability.


# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ![Congratulations Banner](https://github.com/data-umbrella/info/blob/main/images/welcome-bot/BannerCongratulations.jpg?raw=true)

  Congrats on merging your first pull request! :tada:
  We here at _Data Umbrella_ are proud of you! :sparkling_heart: ðŸ’–
  Thank you so much for your contribution :gift: